Parameters:
  DBName:
    Type: String
    Default: MyDB
  DBUsername:
    Type: String
    Default: admin123
  DBPassword:
    Type: String
  DBClass:
    Type: String
    Default: db.t3.micro
  DBAllocatedStorage:
    Type: Number
    Default: 5
Resources:
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '5432'
        ToPort: '5432'
        SourceSecurityGroupName:
          Ref: WebServerSecurityGroup
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:
        Ref: DBName
      Engine: postgres
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword
      DBInstanceClass:
        Ref: DBClass
      AllocatedStorage:
        Ref: DBAllocatedStorage
      VPCSecurityGroups:
        - !GetAtt DBEC2SecurityGroup.GroupId
      PubliclyAccessible: False
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      ImageId: ami-043097594a7df80ec
      KeyName: ec2-key-pair